/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.views.admin.warehouse;

import Helpers.Helper;
import java.awt.Image;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import qlbhgg.controller.SupplierController.SupplierController;
import qlbhgg.controller.TogController.TogController;
import qlbhgg.models.Goods;
import qlbhgg.models.Suppliers;
import qlbhgg.models.TypeOfGoods;
import qlbhgg.ImageHandle.ScaleImage;
import qlbhgg.controller.ProductController.ProductController;


/**
 *
 * @author acer
 */
public class ChangeProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    ScaleImage image = new ScaleImage();
    
    private SupplierController sc = new SupplierController();
    private TogController tc = new TogController();
    private ArrayList<Suppliers> list;
    private ArrayList<TypeOfGoods> listTog;
    private String path = "";
    private static String key;
    private static PanelWarehouse pw;
    private String productCode;
    private int XX,YY;
    public ChangeProduct(String key, PanelWarehouse pw) {
        try {
            this.list = sc.getAllSupplier();
            this.listTog = tc.getAllType();
            this.pw = pw;
            initComponents();
            setVisible(true);
            setLocationRelativeTo(null);
            this.key = key;
            jButton1.setVisible(false);
            path = "";
            setComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(ChangeProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public ChangeProduct(String key, PanelWarehouse pw, String code) {
        try {
            this.list = sc.getAllSupplier();
            this.listTog = tc.getAllType();
            this.pw = pw;
            initComponents();
            setVisible(true);
            setLocationRelativeTo(null);
            this.key = key;
            this.productCode = code;
            
            setComboBox();
            setProduct(productCode);
        } catch (SQLException ex) {
            Logger.getLogger(ChangeProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public Goods getProduct() {
        Goods product = new Goods();
        int indexSup = suppliers.getSelectedIndex();
        int indexType = listT.getSelectedIndex();
        product.setItemname(productName.getText());
        product.setCompanycode(list.get(indexSup).getCompanycode());
        product.setTypecode(listTog.get(indexType).getTypecode());
        product.setAmount(Integer.parseInt(productAmount.getText()));
        product.setUnit(productUnit.getText());
        product.setImportprice(Float.parseFloat(productImport.getText()));
        product.setPrice(Float.parseFloat(productPrice.getText()));
        product.setImageitem(path);
        return product;
    }
    private void setComboBox() throws SQLException {
        
        for (Suppliers s : list) {
            suppliers.addItem(s.getCompanyname());
        }
        for (TypeOfGoods t : listTog) {
            listT.addItem(t.getTypename());
        }
    }
    private void setProduct(String code) throws SQLException {
        ProductController productController = new ProductController();
        
        Goods product = new Goods();
        product = productController.getProduct(code);
        String supplier = sc.getSupplier(product.getCompanycode());
        String type = tc.getType(product.getTypecode());
        productName.setText(product.getItemname());
        productAmount.setText(product.getAmount() + "");
        productUnit.setText(product.getUnit());
        productImport.setText(product.getImportprice() + "");
        productPrice.setText(product.getPrice() + "");
        path = product.getImageitem();
        ImageIcon icon = new ImageIcon(getClass().getResource(product.getImageitem()));
        Image image = icon.getImage().getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(image);
        jLabel9.setIcon(scaledIcon);
        
        suppliers.setSelectedItem(supplier);
        listT.setSelectedItem(type);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jButtonSaveSupplier = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonSelectLogo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        productImport = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        productUnit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        suppliers = new javax.swing.JComboBox<>();
        listT = new javax.swing.JComboBox<>();
        jPanelTitle = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        productName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Nhà cung cấp:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        productAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productAmountKeyTyped(evt);
            }
        });
        jPanel1.add(productAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Số lượng:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Giá bán:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        productPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productPriceKeyTyped(evt);
            }
        });
        jPanel1.add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 190, -1));

        jButtonSaveSupplier.setBackground(new java.awt.Color(102, 178, 255));
        jButtonSaveSupplier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSaveSupplier.setText("Lưu");
        jButtonSaveSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSaveSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Hình ảnh:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 90, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 150, 150));

        jButtonSelectLogo.setBackground(new java.awt.Color(102, 178, 255));
        jButtonSelectLogo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSelectLogo.setText("Chọn");
        jButtonSelectLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSelectLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectLogoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSelectLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 80, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Loại:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Giá nhập:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, -1));

        productImport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productImport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productImportKeyTyped(evt);
            }
        });
        jPanel1.add(productImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 190, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Đơn vị tính:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        productUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(productUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 190, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Xóa sản phẩm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        suppliers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersActionPerformed(evt);
            }
        });
        jPanel1.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, -1));

        listT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(listT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));

        jPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelExit.setBackground(new java.awt.Color(0, 0, 0));
        jLabelExit.setForeground(new java.awt.Color(0, 0, 0));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_4.png"))); // NOI18N
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        jPanelTitle.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 0, 30, 30));

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbhgg/Icon/icons8_overwolf_25px.png"))); // NOI18N
        jLabelTitle.setText("Thông tin sản phẩm");
        jLabelTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabelTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelTitleMouseDragged(evt);
            }
        });
        jLabelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelTitleMousePressed(evt);
            }
        });
        jPanelTitle.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 626, 30));

        jPanel1.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSupplierActionPerformed
        Helper helper = new Helper();
        if(productName.getText().equals("") || productAmount.getText().equals("") || productUnit.getText().equals("") || productImport.getText().equals("") || productPrice.getText().equals("")) {
            helper.sendMessage("Vui lòng nhập đầy đủ thông tin");
            return;
        }
        if(path.equals("")) {
            helper.sendMessage("Vui lòng chọn ảnh !!!");
            return;
        }
        if(!helper.isFloatNumber(productImport.getText()) || !helper.isFloatNumber(productPrice.getText()) || !helper.isIntNumber(productAmount.getText())) {
            helper.sendMessage("Vui lòng nhập đúng định dạng số");
            return;
        }
        try {
            ProductController pc = new ProductController();
            switch(key) {
                case "add":
                    pc.addProduct(this);
                    helper.sendMessage("Thêm sản phẩm thành công");
                    pw.update();
                    this.dispose();
                    break;
                case "update":
                    pc.updateProduct(this, productCode);
                    helper.sendMessage("Cập nhật sản phẩm thành công");
                    pw.update();
                    this.dispose();
                    break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChangeProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSaveSupplierActionPerformed

    private void suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliersActionPerformed

    private void jButtonSelectLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectLogoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        String extension = "";
        int i = filename.lastIndexOf('.');
        if (i >= 0) {
            extension = filename.substring(i+1);
        }
        if(extension.equals("png") || extension.equals("jpg")) {
            String[] parts = filename.split("\\\\");
            boolean check = false;
            for(String item : parts) {
                if(item.equals("ImageProduct") || check) {
                    path += "/" + item;
                    check = true;
                }
            }
            ImageIcon icon = new ImageIcon(filename);
            Image image = icon.getImage().getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(image);
            jLabel9.setIcon(scaledIcon);
        } else {
            Helper helper = new Helper();
            helper.sendMessage("Vui lòng chọn định dạng file png hoặc jpg");
            return;
        }
        
    }//GEN-LAST:event_jButtonSelectLogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String productCode = this.productCode;
            int ret = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa sản phẩm này không ?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(ret != JOptionPane.YES_OPTION) {
                return;
            }
            ProductController pc = new ProductController();
            pc.deleteProduct(productCode);
            Helper helper = new Helper();
            helper.sendMessage("Đã xóa sản phẩm");
            this.dispose();
            pw.update();
        } catch (SQLException ex) {
            Logger.getLogger(ChangeProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void productAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productAmountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_productAmountKeyReleased

    private void productAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productAmountKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_productAmountKeyTyped

    private void productImportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productImportKeyTyped
       if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_productImportKeyTyped

    private void productPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productPriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_productPriceKeyTyped

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_3.png")));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_4.png")));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - XX, y - YY);
    }//GEN-LAST:event_jLabelTitleMouseDragged

    private void jLabelTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTitleMousePressed
        XX = evt.getX();
        YY = evt.getY();
    }//GEN-LAST:event_jLabelTitleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeProduct(key, pw).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSaveSupplier;
    private javax.swing.JButton jButtonSelectLogo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JComboBox<String> listT;
    private javax.swing.JTextField productAmount;
    private javax.swing.JTextField productImport;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JTextField productUnit;
    private javax.swing.JComboBox<String> suppliers;
    // End of variables declaration//GEN-END:variables
}
