/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbhgg.views.admin.bill;

import Helpers.Helper;
import java.sql.SQLException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlbhgg.controller.BillController.BillController;
import qlbhgg.controller.CustomerController.CustomerController;
import qlbhgg.controller.InvoiceDetailsController.InvoiceController;
import qlbhgg.controller.ProductController.ProductController;
import qlbhgg.controller.UserController.UserController;
import qlbhgg.dao.CustomerDao;
import qlbhgg.dao.GoodsDao;
import qlbhgg.dao.InvoicedetailsDao;
import qlbhgg.dao.UsersDao;
import qlbhgg.models.Bill;
import qlbhgg.models.Customers;
import qlbhgg.models.Invoicedetails;
import qlbhgg.models.Users;
import qlbhgg.views.admin.warehouse.ChangeProduct;

/**
 *
 * @author ADMIN
 */
public class ShowBill extends javax.swing.JFrame {

    /**
     * Creates new form ShowBill1
     */
    private static PanelBill pb;
    private static String codeBill;
    private int XX, YY;
    public ShowBill(PanelBill pb, String codeBill) throws SQLException {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
        this.pb = pb;
        this.codeBill = codeBill;
        render();
    }
    private void render() throws SQLException {
        BillController bc = new BillController();
        Bill bill = bc.getBill(codeBill);
        jLabelIdBill.setText(bill.getCodebill());
        Time creationtime = bill.getCreationtime();
        jLabelDateBill.setText(bill.getCreationdate() + " " + creationtime);
        
        Users userCreateBill = UserController.findStaffById(bill.getIduser());
        jLabelStaffBill.setText(userCreateBill.getFullname());
        
        Customers customerBill = CustomerController.findCustomerById(bill.getCustomercode());
        jLabelCustomerName.setText(customerBill.getCustomername());
        jLabelCustomerPhonenumber.setText(customerBill.getPhonenumber());
        jLabelCustomerAddress.setText(customerBill.getAddress());
        jLabelCustomerEmail.setText(customerBill.getEmail());
        
        ArrayList<Invoicedetails>list = InvoiceController.findInvoicedetailsByIdBill(bill.getCodebill());
        float price = 0, discount = 0;
        int count = 0;
        int j = 1;
        for (Invoicedetails iv : list) {
            price += iv.getPrice() * iv.getAmount();
            discount += (iv.getPrice() * iv.getAmount()) / 100 * iv.getDiscount();
        }
        jLabelTotalPrice.setText(String.format("%1$,.0f",price));
        jLabelDiscount.setText(String.format("%1$,.0f",discount));
        jLabelPrice.setText(String.format("%1$,.0f",price - discount));
        
        String[] header = {"STT", "Mã sản phẩm", "Tên sản phẩm", "Giá", "Chiết khấu", "Thành tiền"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        int i = 1;
        for (Invoicedetails iv : list) {
            model.addRow(new Object[]{i++, iv.getItemcode(),ProductController.findProductForBill(iv.getItemcode()).getItemname(),String.format("%1$,.0f",iv.getPrice() * iv.getAmount()), String.format("%1$,.0f",(iv.getPrice() * iv.getAmount()) / 100 * iv.getDiscount()), String.format("%1$,.0f",iv.getPrice()*iv.getAmount() - (iv.getPrice() * iv.getAmount()) / 100 * iv.getDiscount())});
        }
        jTableBill.setModel(model);
        jTableBill.setVisible(true);
        
        jLabelNote.setText(bill.getNote());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabelIdBill = new javax.swing.JLabel();
        jLabelDateBill = new javax.swing.JLabel();
        jLabelStaffBill = new javax.swing.JLabel();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabelCustomerPhonenumber = new javax.swing.JLabel();
        jLabelCustomerAddress = new javax.swing.JLabel();
        jLabelCustomerEmail = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTotalPrice = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelDiscount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jButtonEditBill = new javax.swing.JButton();
        jButtonDeleteBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBill = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanelTitle = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 83, 1227, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ghi chú:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thông tin hóa đơn");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nhân viên bán hàng:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, -1));

        jLabelNote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNote.setText("note: đã trả trước 200k");
        jPanel2.add(jLabelNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 700, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày tạo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Khách hàng");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Họ và tên:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Điện thoại:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Email:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 60, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 10, 170));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Địa chỉ:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 70, -1));

        jLabelIdBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelIdBill.setText("?");
        jPanel2.add(jLabelIdBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 250, -1));

        jLabelDateBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDateBill.setText("?");
        jPanel2.add(jLabelDateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 250, -1));

        jLabelStaffBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelStaffBill.setText("?");
        jPanel2.add(jLabelStaffBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 250, -1));

        jLabelCustomerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCustomerName.setText("?");
        jPanel2.add(jLabelCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 230, -1));

        jLabelCustomerPhonenumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCustomerPhonenumber.setText("?");
        jPanel2.add(jLabelCustomerPhonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 230, -1));

        jLabelCustomerAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCustomerAddress.setText("?");
        jPanel2.add(jLabelCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 230, -1));

        jLabelCustomerEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCustomerEmail.setText("?");
        jPanel2.add(jLabelCustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 230, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, 10, 170));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Thanh toán");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tổng tiền:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 90, -1));

        jLabelTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTotalPrice.setForeground(new java.awt.Color(51, 255, 0));
        jLabelTotalPrice.setText("?");
        jPanel2.add(jLabelTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 170, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Chiết khấu:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 90, -1));

        jLabelDiscount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDiscount.setText("?");
        jPanel2.add(jLabelDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 200, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Tổng thu:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 110, -1));

        jLabelPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(51, 255, 0));
        jLabelPrice.setText("?");
        jPanel2.add(jLabelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 200, -1));

        jButtonEditBill.setBackground(new java.awt.Color(102, 178, 255));
        jButtonEditBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEditBill.setText("Sửa");
        jButtonEditBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditBillActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, -1, -1));

        jButtonDeleteBill.setBackground(new java.awt.Color(102, 178, 255));
        jButtonDeleteBill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDeleteBill.setText("Xóa");
        jButtonDeleteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteBillActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeleteBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, -1, -1));

        jTableBill.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableBill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "ádads", "chuột", "222", "1", "221"},
                {"2", "ssss", "bàn phím", "2", "1", "1"},
                {null, null, "Tổng", "224", "2", "222"}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Giá", "Chiết khấu", "Thành tiền"
            }
        ));
        jTableBill.setFocusable(false);
        jTableBill.setRowHeight(25);
        jTableBill.setSelectionBackground(new java.awt.Color(215, 220, 222));
        jTableBill.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableBill.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableBill);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 1200, 370));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Thông tin hóa đơn");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Mã hóa đơn:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jPanelTitle.setBackground(new java.awt.Color(0, 0, 0));
        jPanelTitle.setForeground(new java.awt.Color(0, 0, 0));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 0));
        jLabelExit.setForeground(new java.awt.Color(0, 0, 0));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_4.png"))); // NOI18N
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlbhgg/Icon/icons8_overwolf_25px.png"))); // NOI18N
        jLabelTitle.setText("Thông tin hóa đơn");
        jLabelTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabelTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelTitleMouseDragged(evt);
            }
        });
        jLabelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelTitleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExit))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteBillActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String codeBill = this.codeBill;
            int ret = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa hóa đơn này không ?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(ret != JOptionPane.YES_OPTION) {
                return;
            }
            BillController bc = new BillController();
            bc.deleteBill(codeBill);
            Helper helper = new Helper();
            helper.sendMessage("Đã xóa hóa đơn");
            this.dispose();
            pb.update();
        } catch (SQLException ex) {
            Logger.getLogger(ChangeProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteBillActionPerformed

    private void jButtonEditBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditBillActionPerformed
        try {
            // TODO add your handling code here:
            EditBill eb = new EditBill(pb,codeBill);
            pb.update();
            this.dispose();
            eb.setDefaultCloseOperation(eb.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(ShowBill.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jButtonEditBillActionPerformed

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_3.png")));
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited

        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_close_window_25px_4.png")));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelTitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTitleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - XX, y - YY);
    }//GEN-LAST:event_jLabelTitleMouseDragged

    private void jLabelTitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTitleMousePressed
        XX = evt.getX();
        YY = evt.getY();
    }//GEN-LAST:event_jLabelTitleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowBill(pb, codeBill).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowBill.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeleteBill;
    private javax.swing.JButton jButtonEditBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCustomerAddress;
    private javax.swing.JLabel jLabelCustomerEmail;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JLabel jLabelCustomerPhonenumber;
    private javax.swing.JLabel jLabelDateBill;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelIdBill;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelStaffBill;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTotalPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableBill;
    // End of variables declaration//GEN-END:variables
}
